### ISSUE TITLE
Circular dep between buster and when.js

### ISSUE THREAD

**Issue by briancavalier** [busterjs/buster#204]
Hey guys, I don't know when this started, but it had to have been after when.js 1.3 was released, since the Travis build was good at that point.  It seems like we have some sort of circular dep now, with buster using when internally, and when using buster as its unit test framework.  It's pretty easy for me to reproduce it:
1. `git clone https://github.com/cujojs/when.git`
2. `cd when`
3. `npm install`

npm dies for me with a circular dependency.  If instead of step 3, I install buster globally, it will install ok, and then `npm test` works just fine.

[Here it is](http://travis-ci.org/#!/cujojs/when/builds/1683898) happening in travis as well.

Any ideas what might be going on and how we can fix it?

**Comment by dominykas** [comment]
Ran a quick test - this is now fixed: https://github.com/npm/npm/issues/2063#issuecomment-154856420
