### ISSUE TITLE
buster's use of uncaughtException conflicts with node 0.8 domains

### ISSUE THREAD

**Issue by ehd** [busterjs/buster#302]
I wrote a [mailing list post](https://groups.google.com/d/msg/busterjs/J2laSsf5-to/kAA2kbyK7YEJ) and detailed the problem in [a gist](https://gist.github.com/fe34db4804100b4a62ef).

Basically it should be possible to tell buster not to catch uncaught exceptions so it won't conflict with the domain module's uncaughtException event handler.

**Comment by dominykas** [comment]
Domains are getting deprecated in node.
