### ISSUE TITLE
Buster's output is truncated

### ISSUE THREAD

**Issue by cowwoc** [busterjs/buster#329]
If I run "node.exe tests/CompanyTest.js" under Maven's exec() plugin I see the full output (even with colors!).

```
CompanyTest: ..
1 test case, 2 tests, 2 assertions, 0 failures, 0 errors, 0 timeouts
Finished in 0.005s
```

By contrast, if I run "buster-test -v" I get the following output:

```
Running tests: My tests
CompanyTest: [INFO] 
```

How does buster-test's output differ from that of node.js? I'm guessing something is wrong in the way Buster is outputting to stdout or stderr.

**Comment by dwittner** [comment]
@cowwoc, can i close this issue?

**Comment by cowwoc** [comment]
I am no longer actively using Buster, so yes you can go ahead.
