### ISSUE TITLE
"Deffert" - assert with promises in asynchronous tests

### ISSUE THREAD

**Issue by johlrogge** [busterjs/buster#339]
Buster has a really nice feature: return a promise for an asynchronous test:

``` javascript
"some test" : function() {
   return when(asyncThingy()).
              then(function(actual){
                 assert.equals(actual, "expected");
              });
}
```
I came up with a pattern to make asserting simpler (I know at least one other person has done something similar so probably pretty obvious):

``` javascript
"some test" : function() {
   return when(asyncThingy()).
              then(deffert.equals("expected"));
}
```

Basically it allows splitting asserts in two parts: first declare your expectations. Each expectation returns a function that accepts the actual value and performs the assert.

Each assert also returns the actual value so that several assertions can be made in sequence:

``` javascript
"some test" : function() {
   return when(asyncThingy()).
              then(deffert.match({key:"value"})).
              then(pluck('otherKey')).
              then(defert.equals("other value"));
   });
}
```

I don't know if there is any other way I missed to do this with existing assertions or if this would be a good extension (or part of the buster core assertions)?

**Comment by meisl** [comment]
...not really understanding anymore what this was about - "finally" is probably what I want to say :)
