### ISSUE TITLE
npm ERR! fetch failed https://github.com/cujojs/when/tarball/1.3.0

### ISSUE THREAD

**Issue by quarterto** [busterjs/buster#351]
Half the time, my Travis build errors with the above. The decision to use whenjs from Github was taken [a year ago](https://github.com/busterjs/buster/issues/15#issuecomment-3981739); since then, when 2.0 is on npm, as well as 1.3. Please consider switching back to when from npm.

**Comment by dominykas** [comment]
This was a problem due to npm's way of doing things. This is fixed in npm@2+ and the next buster release will use when v3 all across the board.
