### ISSUE TITLE
buster-coverage + buster-amd

### ISSUE THREAD

**Issue by gxxcastillo** [busterjs/buster#415]
When I run buster-test I get the "all slaves timed out" message after a long pause.  This problem, however, does not happen if I disable the buster-coverage extension.

Looking around, I found a few old threads that mentioned the similar problems and I was wondering if there's a updated state of affairs?  

https://groups.google.com/forum/#!msg/busterjs-dev/S0E64D4wBqQ/rV870UoSXHcJ
https://github.com/ebi/buster-coverage/issues/10
http://irclogger.com/.buster.js/2013-07-18

**Comment by abhishekbh** [comment]
Just as an update here, the same problem seems to occur with buster-coverage.
I switched to buster-istanbul and we seem to be good.

**Comment by uglymunky** [comment]
ah, shoot, just realized I never responded.  Indeed, buster-istanbul has worked for me as well.
