### ISSUE TITLE
`teamcity` reporter should handle `uncaughtException` and `suite:error`

### ISSUE THREAD

**Issue by dominykas** [busterjs/buster#428]
If the test suite run emits an `uncaughtException` or `suite:error`, they will quietly go down into the void. They exceptions should be printed somewhere.

**Comment by GCheung55** [comment]
`teamcity` reporter is now the `xml` reporter. It looks like the reporter prints out the uncaught exceptions, but buster-test doesn't exist with error code 1, when it should.

**Comment by dominykas** [comment]
stalebot-ing myself.
