### ISSUE TITLE
useFakeServer() returns null object?

### ISSUE THREAD

**Issue by akaias** [busterjs/buster#433]
hi there,

according to the documentation i wanted to create a testcase which mocks my jQuery.ajax call,
but it fails without being mocked.

my testcase:
(function(){
buster.testCase('DateInformationController', {
  testIndexAction:
  {
     setUp: function()
     {
       this.server = this.useFakeServer();
       this.controller = new DateInformationController();
     },
     testIndex: function()
     {
       this.controller.indexAction();
       assert.equals(this.server.requests.length, 1);
     }
  }
}
}());
Error: DateInformationController testIndexAction testIndex
  TypeError: Cannot read property 'requests' of null
    TypeError: Cannot read property 'requests' of null
          at Object.buster.testCase.testIndexAction.testIndex

**Comment by kkirby** [comment]
Is there anyway to have this work on the CL? I'm figured one benefit of mocking XMLHttpRequest would be that it could work on the command line. Is this not the case?

**Comment by kkirby** [comment]
Never mind. It's a limitation of Sinon. https://github.com/cjohansen/Sinon.JS/issues/125
