### ISSUE TITLE
buster/build is broken.

### ISSUE THREAD

**Issue by GCheung55** [busterjs/buster#435]
`buster/build` fails.

```bash
/Users/garrickcheung/Dropbox (Personal)/git/buster/build:95
        if (err) throw err;
                       ^
Error: ENOENT, open '/Users/garrickcheung/git/buster/lodash/lodash'
```

`buster/build` needs an update since buster + deps have been updated.

**Comment by dominykas** [comment]
Works on master and in https://github.com/busterjs/buster/pull/466/files - haven't tried via `buster-dev-env`, but I assume that would probably be broken, alright.
