### ISSUE TITLE
buster-ci should pass the server url to buster test cli

### ISSUE THREAD

**Issue by GCheung55** [busterjs/buster#448]
`buster-ci` config allows for a server object definition, which contains host and port.

Unfortunately, the port is changed from the default of 1111, it doesn't get passed to `buster-test-cli`.

The painful way to get around this is to identify the server as an argv AND a config option of `buster-ci`:

```javascript
module.exports = {
    server: {
        host: 'localhost',
        port: 1212
    }
}
```

```bash
$ buster-ci --server http://localhost:1212
```

We'd have to determine which one has higher priority, config file option or argv. I also suggest that we use the `url` module to parse a string and format an object.

```javascript
var url = require('url')

var server = {
    hostname: 'localhost',
    port: 1111,
    protocol: 'http'
}

// returns http://localhost:1111
url.format(server)

/* returns
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'localhost:1111',
  port: '1111',
  hostname: 'localhost',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://localhost:1111/' }
*/
url.parse('http://localhost:1111')
```

**Comment by dwittner** [comment]
Fixed in version 0.2.1 of buster-ci.
