### ISSUE TITLE
util.print deprecation warnings appearing in reporter output. Replace with console.log.

### ISSUE THREAD

**Issue by GCheung55** [busterjs/buster#452]
node@0.12 is deprecating util.print: https://nodejs.org/api/util.html#util_util_print

Thoughts on replacing `util.print` with `console.log`?

**Comment by dominykas** [comment]
Seeing plenty of these myself... I'm not sure `console.log` is the way to go - my guess is that `util.print` was used, because `console` is hijacked during test runs to intercept the messages? So, probably a correct alternative might be to hook into `process.stdout`.

**Comment by GCheung55** [comment]
I can swap with process.stdout. Do you think a fallback to console.log would be necessary in case process is undefined?

**Comment by dominykas** [comment]
Can the `process` even be `undefined`? If there's `util.print`, I assume it's node code, therefore `process` should be also there. Either way, when I last looked at this, there was some other issue, but I can't recall... maybe sync/async problems... maybe something else. This needs a little bit of doc reading/research to list out what are the differences between the three things (`util`, `console` and `stdout`).

**Comment by GCheung55** [comment]
Perhaps we can use util.log instead?

**Comment by dominykas** [comment]
Docs say `util.log` will have a timestamp prepended... I'd say stdout approach is better, as you mentioned on IRC. I just really don't remember what was the problem with it :)

**Comment by GCheung55** [comment]
I've switched to using process.stdout.

**Comment by GCheung55** [comment]
@dominykas, @augustl, @dwittner, @cjohansen: Thoughts on the change?

**Comment by dominykas** [comment]
I'm all for it - no commit rights, though :)

**Comment by dwittner** [comment]
@GCheung55 , version 0.7.13 of buster-test is released. Please check it.
