### ISSUE TITLE
busterjs/referee: isPromise

### ISSUE THREAD

**Issue by mroderick** [busterjs/buster#459]
Is there any interest in a PR adding `isPromise` to `busterjs/referee`?

**Comment by dwittner** [comment]
I am not sure. Do you think it is useful? Do you need it for testing?

**Comment by dominykas** [comment]
I'm not sure this would even be a good practice, e.g. there's no explicit `instanceof` assertion. Shouldn't you rather let the promise resolve/reject and check it that way?

Either way, what would the test for a promise be? There's a lot more to a promise then just `then()` and it's fairly easy to assert that `then` is a function. Is checking for anything more really possible, considering the plethora of promise libs and also the ES6 standard Promise?

**Comment by dominykas** [comment]
Just noticed that `when` calls this `isPromiseLike` and here's the check: https://github.com/cujojs/when/blob/ccd6970e55006abe73c110fe50eb315f3099bdf9/when.js#L161

**Comment by mroderick** [comment]
`isPromiseLike` would certainly work for the polyfilled scenarios.
