### ISSUE TITLE
buster npm install fails in node 4.x

### ISSUE THREAD

**Issue by gravidThoughts** [busterjs/buster#461]
[Contextify cannot build in node 4.x](https://github.com/brianmcd/contextify/issues/180)

[There is a pull request, but it looks like it is dead in the water.](https://github.com/brianmcd/contextify/issues/180)

A common thought in some of these threads is that the native `vm` implementation in Node 4.x provides the same functionality as Contextify.

How coupled is Buster to Contextify? Would it be fairly easy to switch over to using `vm`? 

Of course this would not work with earlier versions of node. It brings up the interesting problem of semantic versioning. Does npm support the concept of specifying a package based on the version of node?

**Comment by dominykas** [comment]
I'm using buster on node 4.x for a while now - there sure are errors during install (I'll be looking into fixing them), but the overall install seems to work (unless you were to use html reporters, which require old jsdom).

Can you still reproduce the issue / explain the problem in more detail?

**Comment by dominykas** [comment]
Release a `buster-test@0.7.14`, which now uses `jsdom@3.x` - as `contextify@0.1.15` was released some 10 days ago, things now build fine in all nodes (0.10, 0.12, 4, 5), but you might have to upgrade your system build tools, see https://github.com/travis-ci/travis-ci/issues/4771 for details
