### ISSUE TITLE
babel es6 support

### ISSUE THREAD

**Issue by ischoe** [busterjs/buster#477]
I'm getting errors like : 
>> Uncaught exception: SyntaxError: Unexpected token 'const'

when I am running buster test and my code contains es6 syntax.

For production environment I am transpiling all files from es6 to es5 and then run the tests...and that runs fine. But on my local environment I would like to skip that and directly run the tests. Is that possible anyhow with buster ?

**Comment by ischoe** [comment]
seems to be a phantomjs issue not a buster issue....

**Comment by dominykas** [comment]
Seems like you need to transpile your tests before running them in buster.
